# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os: linux
language: r
dist: bionic
jobs:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
cache: packages

r_packages:
  - doMC

r_github_packages:
  - jimhester/covr
  - jimhester/lintr

before_install:
  - sudo apt-get update
  - sudo add-apt-repository -y ppa:opencpu/imagemagick
  - sudo apt-get update
  - sudo apt-get install -y libmagick++-dev

after_success:
  - Rscript -e "lintr::lint_package()"
  - travis_wait Rscript -e "covr::codecov()"
